-- SELECT  
-- RTRIM(TPOPS) as Trabalho,
-- RTRIM(NOPS) as OP,
-- RTRIM(DOPPS) as Desc_Op
-- FROM SLJNENSI with (nolock)
-- WHERE TPOPS LIKE '%TRABALHADO 3,5%%'
-- OR TPOPS LIKE '%TRABALHADO 5%%'


SELECT
RTRIM(NOPS) as OP,
REPLACE(TPOPS, 'TRABALHADO ', '') as Trabalho
FROM SLJNENSI with (nolock)
WHERE TPOPS LIKE '%TRABALHADO 3,5%%'
OR TPOPS LIKE '%TRABALHADO 5%%'
GROUP BY NOPS, TPOPS