IF OBJECT_ID('tempdb..#ULTMOV') IS NOT NULL
    DROP TABLE #ULTMOV;

SELECT MAX(HIS.CIDCHAVES) AS CIDC,
    HIS.CODBARRAS
INTO #ULTMOV
FROM SLJHIS AS HIS WITH (NOLOCK)
WHERE HIS.GRUPOS IN ('110403',
                     '110404',
                     'RESERVA')
    AND HIS.OPERS = 'E'
GROUP BY CODBARRAS;

SELECT HIST.empdopnums,
    HIST.DATAS AS Data,
    -- DIFF IN DAYS TODAY
    DATEDIFF(DAY, HIST.DATAS, GETDATE()) AS DiasConsignado,
    RTRIM(ETI.EMPOS) AS Empresa,
    CONVERT (CHAR (8),
                RTRIM(ETI.CBARS)) AS Cod_Barra,
    RTRIM(ETI.CONTAS) AS Cod_Conta,
    RTRIM(CLI.RCLIS) AS Nome_Conta,
    RTRIM(ETI.CPROS) AS Ref,
    RTRIM(PRO.DPROS) AS Desc_Ref,
    RTRIM(CAB.VENDS) AS Cod_Vend,
    RTRIM(FUN.RCLIS) AS Nome_Vend,
    RTRIM(CAB.DOPES) AS Operacao,
    RTRIM(ITE.TOTAS) AS Valor,
    RTRIM(CAB.codevents) AS Evento,
    RTRIM(CAB.vends) AS Responsavel1,
    RTRIM(RES1.rclis) AS Nome_Responsavel1,
    RTRIM(CAB.resps) AS Responsavel2,
    (CASE
                    WHEN RES2.rclis IS NULL THEN ''
                    ELSE RES2.rclis
                END) AS Nome_Responsavel2,
    CAST(cab.OBSES AS CHAR(150)) Obs
FROM SLJETI AS ETI WITH (NOLOCK)
    LEFT OUTER JOIN SLJCLI AS CLI WITH (NOLOCK) ON CLI.ICLIS = ETI.CONTAS
    LEFT OUTER JOIN SLJPRO AS PRO WITH (NOLOCK) ON PRO.CPROS = ETI.CPROS
    INNER JOIN #ULTMOV AS UMOV ON ETI.CBARS = UMOV.CODBARRAS
    INNER JOIN
    (SELECT HIS.DATAS,
        HIS.EMPDOPNUMS,
        HIS.CIDCHAVES,
        HIS.CODBARRAS
    FROM SLJHIS AS HIS WITH (NOLOCK)
    WHERE HIS.GRUPOS IN ('110403',
                        '110404',
                        'RESERVA')
        AND HIS.OPERS = 'E') AS HIST ON HIST.codbarras = ETI.CBARS
        AND UMOV.CIDC = HIST.CIDCHAVES
    LEFT JOIN SLJEEST AS CAB WITH (NOLOCK) ON CAB.EMPDOPNUMS = HIST.empdopnums
    LEFT JOIN sljcli FUN WITH (NOLOCK) ON FUN.ICLIS = CAB.VENDS
    LEFT JOIN SLJEESTI AS ITE WITH (NOLOCK) ON CAB.EMPDOPNUMS = ITE.EMPDOPNUMS
        AND ITE.CODBARRAS = ETI.CBARS
    LEFT OUTER JOIN SLJCLI AS RES1 WITH (NOLOCK) ON RES1.ICLIS = CAB.VENDS
    LEFT OUTER JOIN sljcli AS RES2 WITH (NOLOCK) ON RES2.iclis = CAB.resps
WHERE ETI.CONTAS <> ''
    AND RTRIM(ETI.CONTAS) NOT IN('CMAT001456', '0126/5', '0625/2', 'CFFL000725', 'CIGU010196', 'CIGU000140')
    AND ETI.GRUPOS IN ('110403',
                     '110404',
                     'RESERVA')