SELECT MAX(HIS.CIDCHAVES) AS CIDC, HIS.CODBARRAS
INTO     ##ULTMOV
FROM SLJHIS AS HIS WITH (NOLOCK)
WHERE    HIS.GRUPOS IN ('110403', '110404', 'RESERVA') AND HIS.OPERS = 'E'
GROUP BY CODBARRAS;
SELECT HIST.empdopnums, HIST.DATAS, ETI.EMPOS AS EMPRESA, CONVERT (CHAR (8), ETI.CBARS) AS COD_BARRA, ETI.CONTAS AS COD_CONTA, CLI.RCLIS AS NOME, ETI.CPROS AS REFERENCIA, PRO.DPROS AS DESC_PRO, CAB.VENDS AS CODVEN, CAB.DOPES AS OPERACAO, ITE.TOTAS AS VALOR, CAB.codevents AS EVENTO, CAB.vends AS RESPONSAVEL1, RES1.rclis AS NOME_RESPONSAVEL1, CAB.resps AS RESPONSAVEL2, (CASE WHEN RES2.rclis IS NULL THEN '' ELSE RES2.rclis END) AS NOME_RESPONSAVEL2, CAST(cab.OBSES AS CHAR(150)) OBS2
FROM SLJETI AS ETI WITH (NOLOCK) LEFT OUTER JOIN SLJCLI AS CLI WITH (NOLOCK) ON CLI.ICLIS = ETI.CONTAS LEFT OUTER JOIN SLJPRO AS PRO WITH (NOLOCK) ON PRO.CPROS = ETI.CPROS INNER JOIN ##ULTMOV AS UMOV ON ETI.CBARS = UMOV.CODBARRAS INNER JOIN (SELECT HIS.DATAS, HIS.EMPDOPNUMS, HIS.CIDCHAVES, HIS.CODBARRAS
    FROM SLJHIS AS HIS WITH (NOLOCK)
    WHERE  HIS.GRUPOS IN ('110403', '110404', 'RESERVA') AND HIS.OPERS = 'E') AS HIST ON HIST.codbarras = ETI.CBARS AND UMOV.CIDC = HIST.CIDCHAVES INNER JOIN SLJEEST AS CAB WITH (NOLOCK) ON CAB.EMPDOPNUMS = HIST.empdopnums INNER JOIN SLJEESTI AS ITE WITH (NOLOCK) ON CAB.EMPDOPNUMS = ITE.EMPDOPNUMS AND ITE.CODBARRAS = ETI.CBARS LEFT OUTER JOIN SLJCLI AS RES1 WITH (NOLOCK) ON RES1.ICLIS = CAB.VENDS LEFT OUTER JOIN sljcli AS RES2 WITH (NOLOCK) ON RES2.iclis = CAB.resps
WHERE  ETI.CONTAS <> '' AND ETI.GRUPOS IN ('110403', '110404', 'RESERVA')